# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "moment*"
      - dependency-name: "protractor"
    groups:
      babel:
        patterns:
          - "@babel/*"
          - "babel-loader"
      bootstrap:
        patterns:
          - "react-bootstrap"
          - "bootstrap"
      eslint:
        patterns:
          - "@typescript-eslint/*"
          - "eslint-*"
          - "eslint"
      react:
        patterns:
          - "@types/react"
          - "@types/react-dom"
          - "react"
          - "react-dom"
    assignees:
      - "jrchudy"
      - "RFSH"
