# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
    allow:
      - dependency-name: "@playwright/test"
    # https://github.com/dependabot/dependabot-core/issues/1778#issuecomment-1988140219
    target-branch: master
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "quarterly"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
    versioning-strategy: "increase"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "@playwright/test"
      # dependencies for old code that we don't need to update:
      - dependency-name: "uglify-js"
      - dependency-name: "q"
      - dependency-name: "@types/q"
      - dependency-name: "moment*"
      # we don't need to update these dependencies as frequently:
      - dependency-name: "@babel/*"
      - dependency-name: "babel-loader"
      - dependency-name: "css-loader"
      - dependency-name: "sass-loader"
      - dependency-name: "prettier"
    groups:
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@eslint/*"
          - "@typescript-eslint/*"
          - "typescript-eslint"
      bootstrap:
        patterns:
          - "react-bootstrap"
          - "bootstrap"
      react:
        patterns:
          - "@types/react"
          - "@types/react-dom"
          - "react"
          - "react-dom"
