import { useEffect, useRef, type JSX } from 'react';

// services
import { ConfigService } from '@isrd-isi-edu/chaise/src/services/config';

// hooks
import useAlert from '@isrd-isi-edu/chaise/src/hooks/alerts';
import { ChaiseAlertType, type ChaiseAlert } from '@isrd-isi-edu/chaise/src/providers/alerts';

// chat feature
import { useChatStore } from '@isrd-isi-edu/chaise/src/hooks/use-chat-store';
import CatalogBar from '@isrd-isi-edu/chaise/src/components/chat/catalog-bar';
import ChatThread from '@isrd-isi-edu/chaise/src/components/chat/chat-thread';
import ChatInput from '@isrd-isi-edu/chaise/src/components/chat/chat-input';

const SEARCH_ONLY_MESSAGE =
  'Search-only mode: results are pulled directly from indexed documentation, NOT generated by AI. ' +
  'Enter keywords or short phrases; natural language questions are not supported in this mode.';

/**
 * The reusable assistant component. Host-agnostic: it only consumes an
 * already-configured ConfigService (it does not bootstrap config or assume an
 * AppWrapper), so any Chaise app can embed it as `<Chat />`. The standalone
 * page (src/pages/chat.tsx) is just one consumer.
 */
const Chat = (): JSX.Element => {
  const init = useChatStore((s) => s.init);
  const hasMessages = useChatStore((s) => s.messages.length > 0);
  const clearHistory = useChatStore((s) => s.clearHistory);
  const error = useChatStore((s) => s.error);
  const clearError = useChatStore((s) => s.clearError);
  const ragModeActive = useChatStore((s) => s.ragModeActive);
  const session = useChatStore((s) => s.session);

  const { addAlert, removeAlert } = useAlert();
  const ragAlert = useRef<ChaiseAlert | null>(null);

  useEffect(() => {
    // assistantBasePath: optional chaise-config pointing at the deriva-mcp-ui
    // backend; empty string means same origin.
    const base = (ConfigService.chaiseConfig as { assistantBasePath?: string }).assistantBasePath ?? '';
    void init(base);
  }, [init]);

  // surface backend/transport errors through the standard Chaise alert service
  useEffect(() => {
    if (!error) return;
    addAlert(error, ChaiseAlertType.ERROR);
    clearError();
  }, [error, addAlert, clearError]);

  // show the search-only notice as a persistent Chaise warning alert while the
  // mode is active; remove it when the mode is turned off. A manual dismiss
  // nulls the ref via onRemove and is not re-added (addAlert/removeAlert are
  // stable, so the effect only re-runs on real state changes).
  useEffect(() => {
    if (ragModeActive) {
      if (ragAlert.current) return;
      const showLoginHint = !!session?.rag_only_when_anonymous && !!session?.login_available;
      const message =
        SEARCH_ONLY_MESSAGE + (showLoginHint ? ' <a href="login">Log in</a> for AI-assisted features.' : '');
      ragAlert.current = addAlert(message, ChaiseAlertType.WARNING, () => {
        ragAlert.current = null;
      });
    } else if (ragAlert.current) {
      removeAlert(ragAlert.current);
      ragAlert.current = null;
    }
  }, [ragModeActive, session, addAlert, removeAlert]);

  // remove a lingering search-only alert when the assistant unmounts
  useEffect(
    () => () => {
      if (ragAlert.current) {
        removeAlert(ragAlert.current);
        ragAlert.current = null;
      }
    },
    [removeAlert],
  );

  return (
    <div className='chat-app'>
      {hasMessages && (
        <div className='chat-header'>
          <button type='button' className='chaise-btn chaise-btn-tertiary chat-new-chat' onClick={() => void clearHistory()}>
            New chat
          </button>
        </div>
      )}
      <CatalogBar />
      <ChatThread />
      <div className='chat-footer'>
        <ChatInput />
        <div className='chat-disclaimer'>
          Responses are generated by AI and may be inaccurate. Verify important results.
        </div>
      </div>
    </div>
  );
};

export default Chat;
