name: Release

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Run semantic-release in dry-run mode'
        required: false
        default: false
        type: boolean

permissions:
  id-token: write  # Required for OIDC
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for trusted publishing and npm provenance
    steps:
      - name: Generate release-app token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.SEMANTIC_RELEASE_APP_CLIENT_ID }}
          private-key: ${{ secrets.SEMANTIC_RELEASE_APP_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm clean-install
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: Install release plugins
        run: npm install --no-save @semantic-release/git
      - name: Release
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: npx semantic-release ${{ inputs.dry-run && '--dry-run' || '' }}